# Numpy မိတ်ဆက်

![numpy](https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/1200px-NumPy_logo_2020.svg.png)

In [1]:
# import keyword သုံးပြီး numpy import လုပ်ခြင်း 
import numpy

In [2]:
# နာမည်တို မှည့်ပြီး import လုပ်ခြင်း
import numpy as np

In [3]:
# NumPy Version စစ်ခြင်း
print(np.__version__) # version attribute ကို သုံးပြီး version စစ်နိုင်သည်။

1.26.4


In [4]:
# np.array function ကို သုံးပြီး list မှတစ်ဆင့် ndarray ကို ဖန်တီးထားခြင်း
arr = np.array([1, 2, 3, 4, 5]) 

print(arr)
print(type(arr))  

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# tuple မှတစ်ဆင့် ndarray ကို ဖန်တီးခြင်း:
arr = np.array((1, 2, 3, 4, 5))

print(arr)
print(type(arr))  

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Dimensions in Array (Array အရွယ်အစားများ)

``ndim`` attribute ကို သုံးပြီး dimension ဘယ်လောက်ရှိလဲဆိုတာပါကြည့်မယ်။

A dimension in arrays is one level of array depth (nested arrays).

**nested array: array အတွင်းမှာ array ထပ်တလဲလဲ ရှိနေခြင်းကို ဆိုလိုသည်။**

![array dimension](NWTQH.png)

## 0-D Arrays
တန်ဖိုး တစ်ခုတည်းသာ ပါသည့် array, Scalar ဟုလည်းခေါ်သည်။

In [6]:
# Create a 0-D array with value 42
arr = np.array(42)
print(arr) # 42
print(arr.ndim) # 0

42
0


## 1-D Arrays (Vectors)
dimension 1 ခု ပါသည့် array ဖြစ်သည်။ uni-dimensional or 1-D array.
အသုံးများပြီး အခြေခံအကျဆုံး array ဖြစ်သည်။

In [7]:
# Create a 1-D array containing the values 1,2,3,4,5:
arr = np.array([1, 2, 3, 4, 5])
print(arr) # [1 2 3 4 5]
print(arr.ndim) # 1

[1 2 3 4 5]
1


## 2-D Arrays (matrix)
dimension 2 ခု ပါသည့် array ဖြစ်သည်။

Matrix တွေကို ဖော်ပြသည့် အခါမှာ သုံးသည်။ 

**data**များကို 2-D Array များဖြင့် အများဆုံးဖော်ပြသည်။

**NumPy has a whole sub module dedicated towards matrix operations called numpy.mat**

![2d array](https://www.simplilearn.com/ice9/free_resources_article_thumb/need-of-two-dimensional-array.png)

In [8]:
# Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr) # [[1 2 3] [4 5 6]]
print(arr.ndim) # 2

[[1 2 3]
 [4 5 6]]
2


## 3-D arrays (tensors)
dimension 3 ခု ပါသည့် array ဖြစ်သည်။

tensor ဟုလည်းခေါ်သည်။

အထူးသဖြင့် အရောင်ပါသည့် RGB ပုံများသည် 3-D arrays (tensors) များ ဖြစ်က

![RGB tensor](https://www.researchgate.net/profile/Bhupendra-Pratap-Singh/publication/282798184/figure/fig15/AS:283989639221249@1444719814399/Color-image-representation-and-RGB-matrix.png)ြသည်။

In [9]:
# Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr) # [[[1 2 3] [4 5 6]]  [[1 2 3] [4 5 6]]]
print(arr.ndim) # 3

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


## Higher Dimensional Arrays (3-D ထက် ပိုလာသည့် array များ)
An array can have any number of dimensions.

arrayများကို ဖန်တီးစဉ် ndmin argument ကို သုံးပြီး လိုချင်သည့် dimensions(အရွယ်အစား)ကို သတ်မှတ်နိုင်သည်။

In [10]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# Performance Comparison: NumPy Arrays vs. Python Lists

In [11]:
import time
python_list1 = list(range(10000000))
python_list2 = list(range(10000000))

np_array1 = np.arange(10000000)
np_array2 = np.arange(10000000)

In [12]:
# Timing Python list operation
start_time = time.time()
result = [python_list1[i] + python_list2[i] for i in range(len(python_list1))]
end_time = time.time()
total_time_arr = end_time - start_time
print(f"Total time for list operation: {total_time_arr:.6f} seconds")

Total time for list operation: 0.648182 seconds


In [13]:
# Timing NumPy array operation
start_time = time.time()
result = np_array1 + np_array2
end_time = time.time()
total_time_arr = end_time - start_time
print(f"Total time for numpy array operation: {total_time_arr:.6f} seconds")

Total time for numpy array operation: 0.069773 seconds
